/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "inVClSNYBQ4",
    title: "How To Make Shahi Paneer At Home | Chef Ranveer",
    videoUrl: "https://youtu.be/inVClSNYBQ4",
    category: "Paneer Recipe",
    author: "Chef Ranveer Brar",
    views: 0,
  },
  {
    _id: "njAWJHGqsPs",
    title: "6 Mouth Watering Snacks Recipes",
    videoUrl: "https://youtu.be/njAWJHGqsPs",
    category: "Snacks",
    author: "Banglar Ranaghor",
    views: 0,
  },
  {
    _id: "WV2GlYJY1TE",
    title: "6 Must Try Indian Sweet Recipes",
    videoUrl: "https://youtu.be/WV2GlYJY1TE",
    category: "Sweets",
    author: "Hebbars Kitchen",
    views: 0,
  },
  {
    _id: "nRPmoioNisI",
    title: "Kadai Paneer Recipe | Easy Kadai Panner At Home",
    videoUrl: "https://youtu.be/nRPmoioNisI",
    category: "Paneer Recipes",
    author: "Chef Ranveer Brar",
    views: 0,
  },
  {
    _id: "glUEnS8J84Q",
    title: "Egg Burji Recipes | How To Make Egg Recipes",
    videoUrl: "https://youtu.be/glUEnS8J84Q",
    category: "Egg Recipes",
    author: "Get Curried",
    views: 0,
  },
  {
    _id: "zMZL_7HlcQc",
    title: "Gajar Ka Halwa | Simple and Easy Recipes",
    videoUrl: "https://youtu.be/zMZL_7HlcQc",
    category: "Sweets",
    author: "Your Food Lab",
    views: 0,
  },
  {
    _id: "J75VQSxOtdo",
    title: "Crispy Roasted Hotel Style Masala Dosa Recipe",
    videoUrl: "https://youtu.be/J75VQSxOtdo",
    category: "South Indian",
    author: "Hebbars Kitchen",
    views: 0,
  },
  {
    _id: "8Lp8qXu5mvo",
    title: "How to Make Crispy French Fries at Home",
    videoUrl: "https://youtu.be/8Lp8qXu5mvo",
    category: "Fast Food",
    author: "Rajshri Food",
    views: 0,
  },
  {
    _id: "Nkndlln0j8c",
    title: "McAloo Tikki Burger Recipe",
    videoUrl: "https://youtu.be/Nkndlln0j8c",
    category: "Fast Food",
    author: "Cooking Shooking",
    views: 0,
  },
  {
    _id: "nnp02lEYi0I",
    title: "Cheesy Potato Nuggets Recipe at Home",
    videoUrl: "https://youtu.be/nnp02lEYi0I",
    category: "Snacks",
    author: "Chef Ranveer Brar",
    views: 0,
  },
  {
    _id: "v4ZRuZgFrZA",
    title: "Easy And Special Kaju Katli Recipe",
    videoUrl: "https://youtu.be/v4ZRuZgFrZA",
    category: "Sweets",
    author: "Chef Ranveer Brar",
    views: 0,
  },
  {
    _id: "nIoIzarlQ1k",
    title: "Idli Sambhar Recipe At Home",
    videoUrl: "https://youtu.be/nIoIzarlQ1k",
    category: "South Indian",
    author: "Hebbars Kitchen",
    views: 0,
  },
  {
    _id: "WlxOy62n584",
    title: "10 Easy Milk Shake Recipe | Summer Refreshment",
    videoUrl: "https://youtu.be/WlxOy62n584",
    category: "Drinks",
    author: "Hands Touch",
    views: 0,
  },
  {
    _id: "wSeVF0YWLV4",
    title: "Paneer Tikka And Green Chutney Recipe",
    videoUrl: "https://youtu.be/wSeVF0YWLV4",
    category: "Paneer Recipe",
    author: "The Terrace Kitchen",
    views: 0,
  },

  {
    _id: "j3pDXY9fqSo",
    title: "Aloo Parantha Recipe At Home",
    videoUrl: "https://youtu.be/j3pDXY9fqSo",
    category: "Parantha",
    author: "Chef Ranveer Brar",
    views: 0,
  },
  {
    _id: "W6K9LD8SOjU",
    title: "4 Hot Beverages Collection For Winters",
    videoUrl: "https://youtu.be/W6K9LD8SOjU",
    category: "Drinks",
    author: "Hebbars Kitchen",
    views: 0,
  },
  {
    _id: "LvAh29JlquA",
    title: "Easy Gujiya Recipe At Home",
    videoUrl: "https://youtu.be/LvAh29JlquA",
    category: "Sweets",
    author: "Masala Kitchen",
    views: 0,
  },
  {
    _id: "w_2eb9uaXns",
    title: "Easy and Instant Dhokhla Recipe",
    videoUrl: "https://youtu.be/w_2eb9uaXns",
    category: "Snacks",
    author: "Home Cooking Show",
    views: 0,
  },
  {
    _id: "YsLX170tDzI",
    title: "Methi Thepla | Easy Brakfast Recipe",
    videoUrl: "https://youtu.be/YsLX170tDzI",
    category: "Parantha",
    author: "Kabita's Kitchen",
    views: 0,
  },
  {
    _id: "gNWW_46qJFA",
    title: "Easy Fafda Recipe At Home",
    videoUrl: "https://youtu.be/gNWW_46qJFA",
    category: "Snacks",
    author: "Chef Ranveer Brar",
    views: 0,
  },
];
